# Generated by Django 5.1.3 on 2026-03-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soru_cevap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='extra_data',
            field=models.JSONField(blank=True, help_text='Gelecekte custom metadata ekleyebilirsin', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='HTML içerik, Tailwind ile kullanılabilir'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='URL için benzersiz slug, otomatik veya manuel', unique=True),
        ),
    ]
