# Generated by Django 5.1.3 on 2026-03-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soru_cevap', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Yayınlanma tarihi, boş bırakılırsa otomatik atanır', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Güncellenme tarihi, boş bırakılırsa otomatik atanır', null=True),
        ),
    ]
