# Generated by Django 5.1.3 on 2026-03-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soru_cevap', '0005_remove_comment_rating_remove_comment_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
