# Generated by Django 5.1.3 on 2026-03-08 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soru_cevap', '0006_alter_comment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='question',
            name='seo_keywords',
        ),
        migrations.AddField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Leave blank to auto-generate from slug'),
        ),
        migrations.AddField(
            model_name='article',
            name='json_ld_override',
            field=models.TextField(blank=True, help_text='Paste custom JSON-LD here to override auto-generated schema'),
        ),
        migrations.AddField(
            model_name='article',
            name='schema_type',
            field=models.CharField(choices=[('Article', 'Article'), ('BlogPosting', 'Blog Post'), ('MedicalWebPage', 'Medical Web Page')], default='Article', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='translation',
            field=models.OneToOneField(blank=True, help_text='Link to the same article in the other language', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated_from', to='soru_cevap.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, help_text='Stored privately; only masked version shown', max_length=254),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1–5 star rating (only meaningful on articles)', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='display_name',
            field=models.CharField(blank=True, help_text='Name shown on the forum (will be semi-masked)', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='email',
            field=models.EmailField(blank=True, help_text='Stored privately; only masked version shown publicly', max_length=254),
        ),
        migrations.AddField(
            model_name='question',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text="Show as 'Anonim Kullanıcı'"),
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('tr', 'TR'), ('en', 'EN')], default='tr', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Full HTML content (Tailwind-compatible)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Meta description (max 160 chars)', max_length=160),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Google title (max 70 chars)', max_length=70),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, help_text='Doctor/Admin answer (triggers FAQ schema when filled)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='article',
            field=models.ForeignKey(blank=True, help_text='Leave blank for global questions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='soru_cevap.article'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['language', 'is_published', 'published_at'], name='soru_cevap__languag_3a0c30_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='soru_cevap__slug_85ca47_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'status'], name='soru_cevap__article_1bde9c_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['question', 'status'], name='soru_cevap__questio_233b26_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status', 'language', 'created_at'], name='soru_cevap__status_5af7db_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['article', 'status'], name='soru_cevap__article_14cff7_idx'),
        ),
        migrations.AddField(
            model_name='like',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='soru_cevap.article'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('article', 'session_key')},
        ),
    ]
