# Generated by Django 5.1.3 on 2026-03-08 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soru_cevap', '0007_like_alter_article_options_alter_comment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Makaleyi yazan doktor/admin. JSON-LD Person schema olarak gönderilir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.URLField(blank=True, help_text='Ana kart görseli (anasayfa listesi + OG image + JSON-LD image). CDN URL veya /static/... yolu. Boş = placeholder.'),
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='Alt text — hem erişilebilirlik hem Google Görseller SEO için', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answered_by',
            field=models.ForeignKey(blank=True, help_text='Cevabı yazan doktor/admin — JSON-LD Person olarak gönderilir', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Boş = slug'dan otomatik"),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Tam HTML içerik. Tailwind class kullanabilirsiniz. İçindeki <img> etiketleri JSON-LD image dizisine otomatik eklenir.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='json_ld_override',
            field=models.TextField(blank=True, help_text='Buraya JSON yapıştırırsanız otomatik üretim tamamen devre dışı kalır. Boş bırakın → sistem Article + AggregateRating + FAQ otomatik üretir.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='schema_type',
            field=models.CharField(choices=[('Article', 'Article'), ('BlogPosting', 'Blog Post'), ('MedicalWebPage', 'Medical Web Page')], default='MedicalWebPage', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Max 160 karakter', max_length=160),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Max 70 karakter', max_length=70),
        ),
        migrations.AlterField(
            model_name='article',
            name='translation',
            field=models.OneToOneField(blank=True, help_text='Diğer dildeki aynı makale (hreflang için)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated_from', to='soru_cevap.article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1–5 yıldız (sadece article yorumlarında anlamlı)', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='soru_cevap.article'),
        ),
        migrations.AlterField(
            model_name='question',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
