# Generated by Django 5.1.3 on 2026-03-08 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soru_cevap', '0009_alter_comment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='soru_cevap__article_28d7e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='soru_cevap__questio_efc7d7_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Makaleyi yazan doktor/admin. JSON-LD Person schema olarak gönderilir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Boş = slug'dan otomatik"),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Tam HTML içerik. Tailwind class kullanabilirsiniz. İçindeki <img> etiketleri JSON-LD image dizisine otomatik eklenir.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.URLField(blank=True, help_text='Ana kart görseli (anasayfa listesi + OG image + JSON-LD image). CDN URL veya /static/... yolu. Boş = placeholder.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='Alt text — hem erişilebilirlik hem Google Görseller SEO için', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='json_ld_override',
            field=models.TextField(blank=True, help_text='Buraya JSON yapıştırırsanız otomatik üretim tamamen devre dışı kalır. Boş bırakın → sistem Article + AggregateRating + FAQ otomatik üretir.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Max 160 karakter', max_length=160),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Max 70 karakter', max_length=70),
        ),
        migrations.AlterField(
            model_name='article',
            name='translation',
            field=models.OneToOneField(blank=True, help_text='Diğer dildeki aynı makale (hreflang için)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated_from', to='soru_cevap.article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1–5 yıldız (sadece article yorumlarında anlamlı)', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answered_by',
            field=models.ForeignKey(blank=True, help_text='Cevabı yazan doktor/admin — JSON-LD Person olarak gönderilir', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'status'], name='soru_cevap__article_1bde9c_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['question', 'status'], name='soru_cevap__questio_233b26_idx'),
        ),
    ]
