# Generated by Django 5.1.3 on 2026-03-08 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soru_cevap', '0010_alter_comment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='soru_cevap__article_1bde9c_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_anonymous',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='soru_cevap.comment'),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, help_text='Kısa konu başlığı. Boş bırakılırsa text truncate kullanılır.', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='json_ld_override',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='article',
            name='translation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translated_from', to='soru_cevap.article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1–5 yıldız (sadece root article yorumlarında)', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'status', 'parent'], name='soru_cevap__article_28d7e4_idx'),
        ),
    ]
