# Generated by Django 5.1.3 on 2026-03-08 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soru_cevap', '0011_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1–5 yıldız (article ve question root yorumlarında)', null=True),
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_likes', to='soru_cevap.question')),
            ],
            options={
                'indexes': [models.Index(fields=['question', 'session_key'], name='soru_cevap__questio_1bfac9_idx')],
                'unique_together': {('question', 'session_key')},
            },
        ),
    ]
