# Generated by Django 5.1.3 on 2026-03-09 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soru_cevap', '0012_alter_comment_rating_questionlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji: 🦷', max_length=8)),
                ('language', models.CharField(choices=[('tr', 'TR'), ('en', 'EN'), ('both', 'Her İkisi')], default='both', max_length=4)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Makale Etiketi',
                'verbose_name_plural': 'Makale Etiketleri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='soru_cevap.articletag', verbose_name='Etiketler'),
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100)),
                ('view_count', models.PositiveSmallIntegerField(default=0)),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Toplam saniye')),
                ('liked', models.BooleanField(default=False)),
                ('commented', models.BooleanField(default=False)),
                ('asked_question', models.BooleanField(default=False)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_behaviors', to='soru_cevap.article')),
            ],
            options={
                'verbose_name': 'Kullanıcı Davranışı',
                'verbose_name_plural': 'Kullanıcı Davranışları',
                'indexes': [models.Index(fields=['session_key', 'last_seen'], name='soru_cevap__session_fc481d_idx')],
                'unique_together': {('session_key', 'article')},
            },
        ),
    ]
