# Generated by Django 5.1.3 on 2026-03-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soru_cevap', '0013_articletag_article_tags_userbehavior'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.URLField(blank=True, help_text="Opsiyonel: soruyla ilgili fotoğraf URL'i"),
        ),
    ]
