# Generated by Django 5.1.3 on 2026-03-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soru_cevap', '0014_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.TextField(blank=True, help_text='Opsiyonel: soruyla ilgili fotoğraf (base64 veya URL)'),
        ),
    ]
