# Generated by Django 5.1.3 on 2025-07-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, max_length=255, null=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gclid', models.CharField(blank=True, max_length=255, null=True)),
                ('conversion_name', models.CharField(max_length=255)),
                ('conversion_time', models.DateTimeField(auto_now_add=True)),
                ('conversion_value', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='TRY', max_length=10)),
            ],
        ),
    ]
