# Generated by Django 5.1.3 on 2025-07-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='client_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
