# Generated by Django 5.1.3 on 2025-07-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion_tracking', '0002_conversion_client_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='conversion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
