# Generated by Django 5.1.3 on 2025-07-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion_tracking', '0003_alter_conversion_conversion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
