# Generated by Django 5.1.3 on 2025-07-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion_tracking', '0004_alter_conversion_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='is_qualified',
            field=models.BooleanField(default=False),
        ),
    ]
