# Generated by Django 5.1.3 on 2025-07-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion_tracking', '0005_conversion_is_qualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='qualification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
