# Generated by Django 5.1.3 on 2025-07-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion_tracking', '0006_conversion_qualification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
