# Generated by Django 5.1.3 on 2025-08-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion_tracking', '0007_alter_conversion_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='actually_called',
            field=models.BooleanField(default=False),
        ),
    ]
