# Generated by Django 5.1.3 on 2026-03-08 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('patient', 'Hasta / Kullanıcı'), ('doctor', 'Doktor'), ('admin', 'Yönetici')], db_index=True, default='patient', max_length=20)),
                ('display_name', models.CharField(blank=True, help_text="Forumda görünen ad. Doktorlar için 'Dr. Ad Soyad'", max_length=150)),
                ('title', models.CharField(blank=True, help_text='Uzmanlık: Ortodontist, Endodontist, Genel Diş Hekimi...', max_length=150)),
                ('bio', models.TextField(blank=True, help_text="Doktor profil açıklaması (JSON-LD'de kullanılır)")),
                ('profile_slug', models.SlugField(blank=True, help_text='Doktor profil URL: /doktor/<slug>/', max_length=200, unique=True)),
                ('sameAs_urls', models.TextField(blank=True, help_text='JSON-LD sameAs linkleri, her satıra bir URL')),
                ('avatar_url', models.URLField(blank=True, help_text='Profil fotoğrafı URL (CDN veya harici)')),
                ('website', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
    ]
