# Generated by Django 5.1.3 on 2026-03-08 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='doctor_approval_requested_at',
            field=models.DateTimeField(blank=True, help_text='Doktor onayı talep tarihi (otomatik)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doctor_approved',
            field=models.BooleanField(default=False, help_text="Doktor onayı. Yalnızca admin True yapabilir. False iken forum'da doktor rozeti ve JSON-LD Person çıkmaz."),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doctor_approved_at',
            field=models.DateTimeField(blank=True, help_text='Onay tarihi (otomatik)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doctor_rejection_reason',
            field=models.TextField(blank=True, help_text='Red sebebi (admin doldurur, kullanıcıya gösterilebilir)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Profil fotoğrafı CDN URL'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text="Forum'da görünen ad. Doktorlar için 'Dr. Ad Soyad'", max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_slug',
            field=models.SlugField(blank=True, help_text='Doktor profil URL: /doktor/<slug>/', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sameAs_urls',
            field=models.TextField(blank=True, help_text='JSON-LD sameAs linkleri — her satıra bir URL'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, help_text='Ortodontist, Endodontist, Genel Diş Hekimi...', max_length=150),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role', 'doctor_approved'], name='accounts_us_role_e8b08a_idx'),
        ),
    ]
