# Generated by Django 5.1.3 on 2025-10-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='card_image_url',
            field=models.URLField(blank=True, help_text='Liste kartı görseli için dış URL'),
        ),
        migrations.AddField(
            model_name='post',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='Detay sayfası posteri için dış URL'),
        ),
        migrations.DeleteModel(
            name='PostFAQ',
        ),
    ]
