# Generated by Django 5.1.3 on 2025-07-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callmelead',
            name='client_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callmelead',
            name='page',
            field=models.CharField(blank=True, default='Ana Sayfa', max_length=255),
        ),
    ]
