# Generated by Django 5.1.3 on 2025-08-17 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_callmelead_client_info_callmelead_page'),
        ('conversion_tracking', '0007_alter_conversion_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gclid', models.CharField(blank=True, max_length=255, null=True)),
                ('client_info', models.JSONField(blank=True, null=True)),
                ('page', models.CharField(blank=True, default='Manuel Onay', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('convert_to_conversion', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('matched_conversion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivals', to='conversion_tracking.conversion')),
            ],
            options={
                'indexes': [models.Index(fields=['gclid'], name='clinic_arri_gclid_77cb3e_idx')],
            },
        ),
    ]
